###
POST http://localhost:8080/api/accounts?email=t@pmail.com&password=pass&type=1

###
GET http://localhost:8080/api/accounts?email=t@pmail.com&password=pass2

###
GET http://localhost:8080/api/accounts/ListAll

###
PUT http://localhost:8080/api/accounts
Content-Type: application/json

{
  "id": 28,
  "password": "pass2",
  "type": 2
}

###
DELETE http://localhost:8080/api/accounts?accountId=23