###
PUT http://localhost:8080/api/category
Content-Type: application/json

{
  "id": 2,
  "name": "tableware"
}

###
POST http://localhost:8080/api/category
Content-Type: application/json

{
  "name": "toys"
}

###
GET http://localhost:8080/api/category